name: Publish

on:
  pull_request:
    branches: [ master ]

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  testPR:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Build and Test
      run: dotnet cake --target=Test --configuration=Release
